services:
  laravel-web:
    build:
      context: "packages/web"
    ports:
      - "${APP_PORT:-8080}:8080"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    env_file: packages/web/.env
    volumes:
      - "./packages/web:/var/www/html"
    networks:
      - vash-net

  #   laravel-reverb:
  #     build:
  #       context: "packages/web"
  #       dockerfile: Dockerfile.reverb
  #     ports:
  #       - "${REVERB_PORT:-8080}:${REVERB_PORT:-8080}"
  #     environment:
  #       WWWUSER: "${WWWUSER}"
  #       IGNITION_LOCAL_SITES_PATH: "${PWD}"
  #     volumes:
  #       - "./packages/web:/var/www/html"
  #     networks:
  #       - vash-net

  osu:
    build: packages/osu
    restart: unless-stopped
    ports:
      - "${OSU_PORT:-3000}:3000"
    networks:
      - vash-net

  pgsql:
    image: "postgres:17"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "vash-pgsql:/var/lib/postgresql/data"
    networks:
      - vash-net
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "${DB_DATABASE}"
        - "-U"
        - "${DB_USERNAME}"
      retries: 3
      timeout: 5s

  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "vash-redis:/data"
    networks:
      - vash-net
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
networks:
  vash-net:
    driver: bridge
  traefik_net:
    external: true

volumes:
  vash-pgsql:
    driver: local
  vash-redis:
    driver: local
