services:
  web:
    build: packages/web
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - DB_HOST=pgsql
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_DATABASE=${DB_DATABASE:-postgres}
      - APP_KEY=${APP_KEY:-base64:brvswgq+bEhxvXY92HkB+lChiSlcU4+vkq+f+tYvmiU=}
    networks:
      - vash-net

  osu:
    build: packages/osu
    env_file: packages/osu/.env
    restart: unless-stopped
    ports:
      - "${OSU_PORT:-3000}:3000"
    networks:
      - vash-net

  discord:
    build: packages/discord
    env_file: packages/discord/.env
    restart: unless-stopped
    networks:
      - vash-net

  pgsql:
    image: postgres:17
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-password}"
      POSTGRES_DB: "${DB_DATABASE:-postgres}"
      POSTGRES_USER: "${DB_USERNAME:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
    volumes:
      - "vash-pgsql:/var/lib/postgresql/data"
    networks:
      - vash-net
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "${DB_DATABASE:-postgres}"
        - "-U"
        - "${DB_USERNAME:-postgres}"
      retries: 3
      timeout: 5s

  redis:
    image: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - "vash-redis:/data"
    networks:
      - vash-net
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
  vash-net:
    driver: bridge

volumes:
  vash-pgsql:
    driver: local
  vash-redis:
    driver: local
