services:
  web:
    build:
      context: ./web
      args:
        OSU_CLIENT_ID: ${OSU_CLIENT_ID}
        OSU_CLIENT_SECRET: ${OSU_CLIENT_SECRET}
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
        JWT_SECRET: ${JWT_SECRET}
        DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID}
        DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
    networks:
      - webnet
    environment:
      - PUBLIC_OSU_CLIENT_ID=${OSU_CLIENT_ID}
      - OSU_CLIENT_SECRET=${OSU_CLIENT_SECRET}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./web
          action: rebuild
    depends_on:
      - socket.io

  socket.io:
    build: ./realtime
    networks:
      - webnet
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    ports:
      - "3001:3001"
    develop:
      watch:
        - path: ./realtime
          action: rebuild

  osu-server:
    build: ./osu-server
    networks:
      - webnet
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OSU_USERNAME=${OSU_USERNAME}
      - OSU_API_KEY=${OSU_API_KEY}
      - OSU_IRC_KEY=${OSU_IRC_KEY}
      - OSU_CLIENT_ID=${OSU_CLIENT_ID}
      - OSU_CLIENT_SECRET=${OSU_CLIENT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - socket.io
    develop:
      watch:
        - path: ./osu-server
          action: rebuild

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./esports.conf:/etc/nginx/conf.d/esports.conf
      - ./nginx_logs:/var/log/nginx
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - socket.io
      - osu-server
      - web
    networks:
      - webnet
    develop:
      watch:
        - path: ./nginx.conf
          action: sync+restart
          target: /etc/nginx/nginx.conf
        - path: ./esports.conf
          action: sync+restart
          target: /etc/nginx/conf.d/esports.conf

  minecraft-hub:
    build: ./minecraft/hub
    ports:
      - "25565:25565"
    networks:
      - webnet
    develop:
      watch:
        - path: ./minecraft/hub
          action: rebuild
    volumes:
      - ./minecraft/hub/plugins:/server/plugins
      - ./minecraft/hub/world:/server/world
      - ./minecraft/hub/server.properties:/server/server.properties
      - ./minecraft/hub/world_nether:/server/world_nether
      - ./minecraft/hub/world_the_end:/server/world_the_end
      - ./minecraft/hub/permissions.yml:/server/permissions.yml

networks:
  webnet:
    driver: bridge
