services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt # Mount certificates
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

  web:
    build: ./web
    networks:
      - webnet

  realtime:
    build: ./realtime
    networks:
      - webnet

  osu-server:
    build: ./osu-server
    networks:
      - webnet

  # discord:
  #   build: ./discord

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./html:/var/www/html
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
