services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

  web:
    build: ./web

  osu-server:
    build: ./osu-server

  realtime:
    build: ./realtime

  # discord:
  #   build: ./discord

networks:
  webnet:
