version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

  app:
    image: my-app:latest
    environment:
      - APP_ENV=production
    networks:
      - webnet

networks:
  webnet:
