name: Deploy to Testing

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Testing
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} -p ${{ secrets.SERVER_PORT }} << 'EOF'
            cd /opt/vash-esports
            git pull origin test
            docker compose -f docker/compose.yml -f docker/compose.test.yml up -d --build
          EOF
